### ISSUE TITLE
auth.failed.no_such_user warning

### ISSUE THREAD

**Issue by grufocom** [caltechads/nginx-ldap-auth-service#11]
Hi, I just gut ldap-auth service to connect to my AD server with the admin-account.
But when I try to login with the login form, I get the error that the user dose not exist.

2025-06-24T08:22:20.108488Z [warning  ] auth.failed.no_such_user       [nginx_ldap_auth] host=*** realm=Restricted remote_ip=*** target=/ username=administrator

But it is the same user with whom the connection to the AD server was made.

My environment settings are like that:

ldap_basedn=DC=example-eu,DC=example,DC=eu
ldap_binddn=CN=Administrator,CN=Users,DC=example-eu,DC=example,DC=eu
ldap_disable_referrals=true
ldap_uri=ldap://srv001.example-eu.example.eu:389

ldapsearch with those settings is fine!

Would be great to get a hint to get the auth working!

**Comment by cmalek** [comment]
Could you post any exceptions or logs that you got?

**Comment by cmalek** [comment]
Also, please give me the ldapsearch line you're using, minus any passwords.

**Comment by grufocom** [comment]
I also noticed that the use of --env-file does not work.
the parameter "--env-file /root/ldap-auth.env" does not work, I have to do "export $(cat /root/ldap-auth.env | xargs)" so that the variables are taken over by nginx-ldap-auth.

**Comment by cmalek** [comment]
I can see from your `ldapsearch` line that you are not using StartTLS (missing the ``-ZZ`` flag)i so you're using an unencrypted connection to your LDAP server.  Try setting `LDAP_STARTLS=False`.   I assume everyone encrypts all connections so I set it to `True` by default.

I'm sorry, looks like the docs are wrong, saying that the default is ``True``.  I'll fix that.

**Comment by cmalek** [comment]
I've released v2.1.8, and the docs are correct now.  I'm sorry for your trouble.  Tell me if setting `LDAP_STARTTLS=False` helps.

**Comment by grufocom** [comment]
great - that works for my administrator user!
but with normal users it does not - I think it is because they are in an OU and not directly in CN=Users - I am not sure what I have to change to satisfy this.

tried with:
LDAP_USER_BASEDN='OU=NoAppdataRedirection,OU=Example-AT,OU=Users,OU=MyBiz,DC=example-eu,DC=example,DC=eu'

**Comment by cmalek** [comment]
Sorry, you can't.  `nginx-ldap-auth-service` is really meant for authenticating users all under the same basedn.

You could do this by setting up two different instances of nginx-ldap-auth-service with different basedns, with corresponding virtualhosts for admin and normal users,

**Comment by grufocom** [comment]
that's what i was afraid of, the problem is that we have a rather complex structure and the separation between admin and other users doesn't go far enough. the other users are divided into many more groups! :-)

does the nginx-ldap-auth service actually get the group membership of the users?

despite the possibility of separating admins and users via two instances, i still have the problem that admins work, but normal users do not.

**Comment by cmalek** [comment]
I'm saying that admins work and others do not because you have different base dns for the two types of users.  `nginx-ldap-auth-service` doesn't support that.

My only solution for you is what I said here https://github.com/caltechads/nginx-ldap-auth-service/issues/11#issuecomment-3005921907

Have an admin login virtualhost and a regular user virtualhost.

**Comment by kblum** [comment]
Hi @grufocom 

I have used `nginx-ldap-auth-service` to put a service behind Active Directory at a client. It is currently running in production.

The `LDAP_BASEDN` environment variable is kept broad and will match any user.

The `LDAP_AUTHORIZATION_FILTER` environment variable is then used to determine if an authenticated user is authorized.
The `LDAP_AUTHORIZATION_FILTER` value is used to perform an LDAP search (if set).
So this should be more flexible than just using the `LDAP_BASEDN` (it did solve the issues that I experienced with AD integration).

https://github.com/caltechads/nginx-ldap-auth-service/blob/0218512c05cf7efbf2c9fb9c51560be3876f13c6/nginx_ldap_auth/app/models.py#L172-L180

Here is a simplified/redacted version of the configuration:

```
# LDAP server settings
LDAP_URI: "ldap://example.corp:389"
LDAP_BASEDN: "ou=Users,o=AUTH"
LDAP_STARTTLS: "false"
LDAP_BINDDN: "cn=ro_svc_acc,ou=services,o=auth"
LDAP_PASSWORD: "PASSWORD"

# LDAP user search settings
LDAP_USERNAME_ATTRIBUTE: "cn"
LDAP_FULL_NAME_ATTRIBUTE: "fullname"
LDAP_GET_USER_FILTER: "({username_attribute}={username})"
LDAP_AUTHORIZATION_FILTER: "(&(objectClass=user)({username_attribute}={username})(groupMembership=cn=LDAP_GROUP,ou=DEPARTMENT,ou=ARM,ou=Groups,o=AUTH))"
```

The “LDAP_GROUP” value in the `LDAP_AUTHORIZATION_FILTER` environment variable is the AD group to use for access.
